[package]
name = "collector"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
toml = { workspace = true }
sqlite = { workspace = true }
clock = { path = "../clock" }
weather_err = { path = "../weather_err" }
config = { path = "../config" }
